version: '3.8'

services:
  app:
    build: .
    container_name: real-time-overlay-app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
